<?php
/**
 * SmartSystems
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to office@smartsystems.ro so we can send you a copy immediately.
 *
 *
 * @category   SmartSystems
 * @package    SmartSystems_Epayment
 * @copyright  Copyright (c) 2009 SmartSystems(http://www.smartsystems.ro)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to ePayment website when you place an order.') ?>
        </li>
    </ul>
</fieldset>